### ISSUE TITLE
Code

### ISSUE THREAD

**Issue by Guzpenha** [Georgetown-IR-Lab/curricula-neural-ir#1]
Hi is there a way to access the code?

**Comment by seanmacavaney** [comment]
Oops, I never got around to pushing the code from my private repo to the public version. Thanks for the heads up!

I updated this repo with trained models, runs, and the configurations you'll need to run it in [OpenNIR](https://github.com/Georgetown-IR-Lab/OpenNIR) ([which now has the code for this paper](https://github.com/Georgetown-IR-Lab/OpenNIR/pull/23)).

Let me know if you encounter any issues!
